# Generated by Django 3.0.3 on 2020-04-20 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('address', models.TextField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('open', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('pic', models.ImageField(upload_to='restaurant/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminview.City')),
                ('fooditem', models.ManyToManyField(to='adminview.Fooditem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantview.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=False)),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminview.Fooditem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantview.Restaurant')),
            ],
        ),
    ]
