# Generated by Django 3.0.2 on 2020-04-22 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('adminview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('fooditem',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='adminview.Fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('address', models.TextField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('open', models.BooleanField(
                    choices=[(True, 'Open'), (False, 'Close')],
                    default=False)),
                ('active', models.BooleanField(
                    choices=[(True, 'Active'), (False, 'Deactive')],
                    default=False)),
                ('pic', models.ImageField(blank=True, null=True,
                                          upload_to='restaurant/')),
                ('city',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='adminview.City')),
                ('fooditem',
                 models.ManyToManyField(through='restaurantview.Menu',
                                        to='adminview.Fooditem')),
                ('parent', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.CASCADE,
                                             to='restaurantview.Restaurant')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='restaurantview.Restaurant'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(
                    choices=[(True, 'Available'), (False, 'Not Available')],
                    default=False)),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='restaurantview.Restaurant')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
