# Generated by Django 3.0.5 on 2020-04-30 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('restaurantview', '0002_auto_20200429_1037'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
            ],
        ),
    ]
