# Generated by Django 3.0.5 on 2020-04-29 10:37

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurantview', '0002_auto_20200429_1037'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('Order', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='restaurantview.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='restaurantview.Delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(
                choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'),
                         (3, 'Delivered'), (4, 'placed')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
