# Generated by Django 3.0.5 on 2020-04-30 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cart', '0002_auto_20200429_1037'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
