# Generated by Django 3.0.3 on 2020-04-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantview', '0001_initial'),
        ('adminview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelRestaurantRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantview.Restaurant')),
            ],
        ),
    ]
